# Generated by Django 5.2.11 on 2026-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('native_name', models.JSONField(blank=True, null=True)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('currencies', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
